### ISSUE TITLE
Download won’t work

### ISSUE THREAD

**Issue by anon-jpg** [ZiniTevi/movieapps#2]
Because streams are slow to cast to Chromecast (in comparison with other apps) I wanted to download first and stream then, but that won’t work. Just my feedback. Love the app and thanks for the latest update.

![24E240B7-5542-41E5-B898-F70C82B14ECD](https://user-images.githubusercontent.com/54095073/67961353-e6db3700-fbfb-11e9-92fe-f8471922403a.png)

**Comment by anon-jpg** [comment]
Please add a feature when apps kills itself and reopen that its first looking if already connected to the Chromecast so you can pause when that bug occurs

**Comment by ZiniTevi** [comment]
Hello,
We are fixing the download problem for next next release. please wait for update!
We will consider about ChromeCast feature that you suggested.
Thanks!
